"""Short-lived, loopback-only connection page. Never returns credentials to MCP."""
import hmac
import imaplib
import json
import re
import secrets
import smtplib
import time
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

from keychain import Keychain


def normalize_password(value):
    if not isinstance(value, str) or len(value) > 64:
        raise ValueError("Use the app-specific password generated by Apple")
    compact = re.sub(r"[- ]", "", value.strip())
    if not re.fullmatch(r"[a-z]{16}", compact):
        raise ValueError("Use the 16-letter app-specific password generated by Apple")
    return "-".join(compact[i:i + 4] for i in range(0, 16, 4))


class SetupError(RuntimeError):
    """Only fixed, secret-free receipts may cross the HTTP boundary."""
    MESSAGES = {
        "invalid_input": "Enter your primary iCloud mailbox address and the 16-letter app-specific password generated by Apple. Do not use your Apple Account password.",
        "verification_failed": "Apple could not verify this mailbox. Check your primary iCloud Mail address and generate a new app-specific password. Nothing was saved.",
        "network_failed": "Could not reach Apple's mail servers securely. Check your internet connection and try again. Nothing was saved.",
        "keychain_failed": "Apple verified the mailbox, but macOS Keychain access failed. Allow Keychain access if prompted, unlock your Keychain, and try again. Account settings were not changed.",
        "config_failed": "Could not save the local account settings. The previous Keychain credential was restored. Check local file permissions and try again.",
        "repair_required": "The save failed and the previous Keychain credential could not be restored. Your local connection needs repair. Reopen setup and connect again; allow Keychain access if prompted.",
        "stale_configuration": "Your account settings changed while this page was checking the mailbox. This page saved nothing. Reopen setup to use the latest settings.",
        "local_settings_failed": "Could not read or lock your local account settings. Check file permissions, close other setup pages, and reopen setup.",
    }

    def __init__(self, code):
        self.code = code
        super().__init__(self.MESSAGES[code])


def _network_error(error):
    # MailError suppresses display of its source, but retains the typed context.
    # Never classify by server-supplied text or relay it to the browser.
    seen = set()
    for _ in range(8):
        if error is None or id(error) in seen:
            break
        seen.add(id(error))
        if isinstance(error, imaplib.IMAP4.abort):
            return True
        if isinstance(error, smtplib.SMTPException):
            return isinstance(error, (smtplib.SMTPServerDisconnected, smtplib.SMTPConnectError))
        if isinstance(error, OSError):
            return True
        error = error.__cause__ or error.__context__
    return False


def connect(core, store, account, password):
    try:
        password = normalize_password(password)
        account = core._email_address(account, "account_address", required=True)
    except (ValueError, TypeError):
        raise SetupError("invalid_input") from None
    try:
        with core.account_config_lock():
            revision = core.account_config_revision()
            old = core._load_config()
            if old and old.get("account_address") == account:
                config = dict(old)
            else:
                config = {"version": core.CONFIG_VERSION, "account_address": account,
                          "imap_username": "", "default_from": account,
                          "allowed_from": [], "display_name": ""}
            config = core._validate_config(config)
    except Exception:
        raise SetupError("local_settings_failed") from None
    try:
        with core.account_session(config, password):
            core.validate_account({})
    except Exception as error:
        code = "network_failed" if _network_error(error) else "verification_failed"
        raise SetupError(code) from None
    try:
        with core.account_config_lock():
            if core.account_config_revision() != revision:
                raise SetupError("stale_configuration")
            try:
                previous = store.get(account)
                store.set(account, password)
            except Exception:
                raise SetupError("keychain_failed") from None
            try:
                core._write_config(config)
            except Exception:
                try:
                    if previous is None:
                        store.delete(account)
                    else:
                        store.set(account, previous)
                except Exception:
                    raise SetupError("repair_required") from None
                raise SetupError("config_failed") from None
    except SetupError:
        raise
    except Exception:
        raise SetupError("local_settings_failed") from None


class SetupServer(HTTPServer):
    def __init__(self, core, store, lifetime=600):
        self.core, self.store = core, store
        self.token = secrets.token_urlsafe(32)
        self.path = "/" + secrets.token_urlsafe(24)
        self.deadline = time.monotonic() + min(lifetime, 600)
        self.connected = False
        self.nonce = secrets.token_urlsafe(24)
        super().__init__(("127.0.0.1", 0), Handler)
        self.origin = "http://127.0.0.1:%d" % self.server_port
        self.timeout = .5

    def get_request(self):
        sock, address = super().get_request()
        sock.settimeout(min(5, max(.01, self.deadline - time.monotonic())))
        return sock, address

    def handle_error(self, request, client_address):
        pass  # HTTP errors must never dump credential-bearing locals or requests.

    def run(self):
        while not self.connected and time.monotonic() < self.deadline:
            self.handle_request()


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):
        pass

    def send_error(self, code, message=None, explain=None):
        self.reply(code, {"error": "Invalid connection request"})

    def reply(self, status, payload, html=False):
        body = payload.encode() if html else json.dumps(payload).encode()
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8" if html else "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Content-Security-Policy", "default-src 'none'; script-src 'nonce-%s'; style-src 'nonce-%s'; connect-src 'self'; form-action 'none'; frame-ancestors 'none'; base-uri 'none'" % (self.server.nonce, self.server.nonce))
        self.end_headers()
        self.wfile.write(body)

    def valid(self):
        s = self.server
        return (time.monotonic() < s.deadline and not s.connected and
                self.headers.get_all("Host") == [s.origin.removeprefix("http://")] and
                self.path == s.path)

    def do_GET(self):
        if not self.valid():
            return self.reply(403, {"error": "Connection page expired or invalid"})
        page = Path(__file__).with_name("setup.html").read_text()
        self.reply(200, page.replace("{{NONCE}}", self.server.nonce), html=True)

    def do_POST(self):
        if (not self.valid() or self.headers.get_all("Origin") != [self.server.origin] or
                self.headers.get("Content-Type") != "application/json" or
                self.headers.get("Transfer-Encoding") is not None or
                not hmac.compare_digest(self.headers.get("X-Setup-Token", "").encode(), self.server.token.encode())):
            return self.reply(403, {"error": "Connection page expired or invalid"})
        lengths = self.headers.get_all("Content-Length", [])
        if len(lengths) != 1 or not lengths[0].isdigit() or not 0 < int(lengths[0]) <= 2048:
            return self.reply(413, {"error": "Invalid request size"})
        try:
            data = json.loads(self.rfile.read(int(lengths[0])))
            if not isinstance(data, dict) or set(data) != {"account", "password"}:
                raise ValueError()
            normalize_password(data["password"])
            if not isinstance(data["account"], str) or len(data["account"]) > 320:
                raise ValueError()
        except (ValueError, TypeError, OSError):
            return self.reply(400, {"error": "Enter your iCloud mailbox address and a 16-letter Apple app-specific password. Do not use your Apple Account password."})
        try:
            core = self.server.core
            deadline = core._ACTIVE_DEADLINE.set(core.OperationDeadline(
                seconds=min(90, max(.01, self.server.deadline - time.monotonic()))))
            try:
                connect(core, self.server.store, data["account"], data["password"])
            finally:
                core._ACTIVE_DEADLINE.reset(deadline)
        except SetupError as error:
            return self.reply(400, {"error": str(error), "code": error.code})
        except Exception:
            return self.reply(400, {"error": "Connection could not complete. Reopen setup and try again.", "code": "setup_failed"})
        self.server.connected = True
        self.reply(200, {"connected": True})


def main():
    import os
    import sys
    import threading
    import server as core
    # A hard process boundary also bounds browser/Keychain system dialogs.
    watchdog = threading.Timer(600, lambda: os._exit(0))
    watchdog.daemon = True
    watchdog.start()
    try:
        with SetupServer(core, Keychain()) as server:
            if not webbrowser.open(server.origin + server.path + "#" + server.token):
                raise RuntimeError("Browser unavailable")
            print("READY", flush=True)
            os.close(sys.stdout.fileno())
            server.run()
    except Exception:
        try:
            print("ERROR", flush=True)
        except OSError:
            pass
        return 1
    finally:
        watchdog.cancel()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
